name: parser
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  analyzer: ^5.6.0
  codemod: ^1.0.11
  docstring_generator_annotator: ^1.0.2
  js: ^0.6.5
